DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS device;
DROP TABLE IF EXISTS videos;


CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE device (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  dev_type TEXT NOT NULL,
  dev_IP TEXT NOT NULL,
  dev_PORT TEXT NOT NULL,
  dev_character TEXT UNIQUE NOT NULL,
  endpoints TEXT NOT NULL,
  animations TEXT NOT NULL
);

CREATE TABLE videos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  folder TEXT NOT NULL,
  file_name TEXT NOT NULL,
  dest_folder TEXT NOT NULL,
  dest_ip TEXT NOT NULL,
  dest_user TEXT NOT NULL,
  dest_password TEXT NOT NULL,
  character_type TEXT NOT NULL,
  cur_state TEXT NOT NULL
 );
